version: '3.9'

services:
  # Dịch vụ cho ứng dụng Spring Boot
  e-commerce-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=ECommerceDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: lamproA2214@
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - e-commerce-network

  # Dịch vụ cho SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: lamproA2214@
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    networks:
      - e-commerce-network
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount file init.sql
    command: /opt/mssql/bin/sqlservr

volumes:
  mssql_data:

networks:
  e-commerce-network:
    driver: bridge
