spring.application.name=ECommerce
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ECommerceDB;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=123456

spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.repositories.enabled=true


#cloudinary config

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
#cloudinary.cloud-name=dnfjw5noh
#cloudinary.api-key=785966883137725
#cloudinary.api-secret=wuI6SvIPsR-nFV05w1MG2LSX-q8

vietqr.clientId=${VIETQR_CLIENT_ID}
vietqr.apiKey=${VIETQR_API_KEY}
#vietqr.clientId=14b5faf9-15f5-4060-acd3-42bc8f9d3285
#vietqr.apiKey=554606ff-9822-4e8b-bec7-f8f0939b8f6d


spring.mail.host = smtp.gmail.com
spring.mail.port = 587

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.username=mtuan120304@gmail.com
#spring.mail.password=citm udhe cdhl wnlx
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true